### ISSUE TITLE
npm version of this library?

### ISSUE THREAD

**Issue by paradite** [nadavshemesh/angular2-click-to-edit#1]
Hi, this is a very useful library that I was looking for.
I noticed that on npm, it says `1.0.52 is the latest of 52 releases`. However, there are no releases on GitHub and the `package.json` shows `"version": "1.0.35"`.

Is there a reason why the versions differ from GitHub and npm? Maybe you have made some changes and forgot to push to GitHub?

Thanks for your work.

**Comment by nadavshemesh** [comment]
Hey, thanks for calling my attention on this! i updated the repo 👍
